---
# Database connection parameters
username: 'postgres'
password: 'postgres'
host: 'localhost'
port: '5432'
database: 'xero-case-study-db'
schema: 'db'
# Database objects
objects:
  customers:
    description: This table contains one row per customer
    columns:
      id:
        dtype: 'String'
        description: 'Unique customer identifier'
        primary_key: True
      name:
        description: 'Name of customer'
        dtype: 'String'
      phone_no:
        description: 'Customer phone number'
        dtype: 'String'
      address:
        description: 'Address of customer'
        dtype: 'String'
  orders:
    description: This table contains one row per order
    columns:
      id:
        dtype: 'String'
        description: 'Unique order identifier'
        primary_key: True
      customer_id:
        dtype: 'String'
        description: 'Unique customer identifier'
      product:
        description: 'The product that has been ordered'
        dtype: 'String'
      quantity:
        description: 'Quantity ordered'
        dtype: 'Integer'
      price_per_unit:
        description: 'The per-unit price for this product'
        dtype: 'Numeric'
  invoices:
    description: This table contains one row per invoice
    columns:
      id:
        dtype: 'String'
        description: 'Unique invoice identifier'
        primary_key: True
      order_id:
        dtype: 'String'
        description: 'Unique order identifier'
      name:
        description: 'Name of customer'
        dtype: 'String'
      address:
        description: 'Address of customer'
        dtype: 'String'
      amount_payable:
        description: 'Amount payable'
        dtype: 'Numeric'
# Database trigger functions
trigger_functions:
  - |
    CREATE OR REPLACE FUNCTION db.generate_invoice()
    RETURNS TRIGGER AS
    $$
      BEGIN
        INSERT INTO db.invoices (id, order_id, name, address, amount_payable)
        SELECT
          uuid_generate_v1() AS id,
          orders.id AS order_id,
          customers.name,
          customers.address,
          orders.quantity*orders.price_per_unit AS amount_payable
        FROM (SELECT NEW.*) orders
        INNER JOIN db.customers customers
        ON orders.customer_id = customers.id
        ON CONFLICT DO NOTHING;
        RETURN NULL;
      EXCEPTION WHEN OTHERS THEN
        RETURN NULL; -- Do nothing.
      END;
    $$
    LANGUAGE PLPGSQL;
    DROP TRIGGER IF EXISTS generate_invoice ON db.orders;
    CREATE TRIGGER generate_invoice
    AFTER INSERT ON db.orders
    FOR EACH ROW EXECUTE PROCEDURE db.generate_invoice();
