---
# Database connection parameters
username: 'postgres'
password: 'postgres'
host: 'localhost'
port: '5432'
database: 'xero-case-study-db'
schema: 'test2'
# Database objects
objects:
  orders:
    description: This table contains one row per order
    columns:
      order_id:
        dtype: 'String'
        comment: 'Unique order identifier'
        primary_key: True
      product:
        comment: 'The product that has been ordered'
        dtype: 'String'
      quantity:
        comment: 'Quantity ordered'
        dtype: 'Integer'
      price_per_unit:
        comment: 'The per-unit price for this product'
        dtype: 'Numeric'
