FROM python:3.8
WORKDIR /code
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src/ src/
CMD python -m src.viz.generate_kedro_viz_json ; python -m kedro viz --host viz --load-file src/viz/viz.json
