---
# Database connection parameters
username: 'postgres'
password: 'postgres'
host: 'db_infra'
database: 'dataplatform-lite-db'
# API secrets and users
secret_key: <API secret key. Run "openssl rand -hex 32" to generate this>
users:
  <name for this user>:
    username: '<a user name>'
    full_name: '<full name>'
    email: '<email>'
    hashed_password: '<Hashed password. Follow these instructiong to generate: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/#hash-and-verify-the-passwords>'
    disabled: <True or False. Must be True in order for this user to access>
    access_tier: <1, 2, or 3. 1 is highest access level, 3 is lowest.>
# Database objects
objects:
  <name for this object>:
    description: <object description>
    api:
      - <get or post. Use this to automatically generate API endpoints.>
    access_tier: <1, 2 or 3. This sets the access level>
    columns:
      <column name>:
        dtype: <Data type - must be a sqlalchemy data type https://docs.sqlalchemy.org/en/14/core/types.html>
        description: <Column description>
        pii: <True or False>
        primary_key: <True or False>
# Database trigger functions
trigger_functions:
  - |
    <SQL trigger functions go here. Refer to examples/\*/config.yml for some examples of this. Full documentation is available here: https://www.postgresql.org/docs/12/plpgsql-trigger.html>
